version: '3.8'

services:
  front:
    build:
      dockerfile: "Dockerfile"
    volumes: 
      - ./:/app:rw,cached
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true